export const USER_PATTERNS = {
  FIND_ALL: 'FIND_ALL',
  FIND_BY_ID: 'FIND_BY_ID',
  UPDATE: 'UPDATE',
  CREATE: 'CREATE',
  REMOVE: 'REMOVE',
  FIND_BY_EMAIL: 'FIND_BY_EMAIL',
  FIND_ONE: 'FIND_ONE',
};
