export const BOOK_PATTERNS = {
  FIND_ALL: 'FIND_ALL',
  FIND_ONE: 'FIND_ONE',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  REMOVE: 'REMOVE',
  GET_PRICE_IN_CURRENCY: 'GET_PRICE_IN_CURRENCY',
  EXPORT_TO_SHEETS: 'EXPORT_TO_SHEETS',
};
