export const SALE_PATTERNS = {
  FIND_ALL: 'FIND_ALL',
  FIND_ONE: 'FIND_ONE',
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  REMOVE: 'REMOVE',
  EXPORT_TO_DOCS: 'EXPORT_TO_DOCS',
  ADD_TO_CALENDAR: 'ADD_TO_CALENDAR',
  GET_CALENDAR_EVENTS: 'GET_CALENDAR_EVENTS',
};
